name: Scrambled Signal Productions
favicon: null
layout_spectrum: 0.433958976296708
typography_spectrum: 0.6714571218471974
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#101010'
    - '#bdc1c2'
    - '#72211d'
    - '#3a80b1'
  brandStrength: 1
  lightness: 0.10221445257775486
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
